spring.application.name=wms-server
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update

jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=1209600000

security.login.max-fail-count=5
security.login.lock-duration-minutes=30
