services:
  redis:
    image: redis:7-alpine
    container_name: wms-redis
    ports:
      - "6379:6379"
    volumes:
      - wms-redis-data:/data

  postgres:
    image: postgres:17-alpine
    container_name: wms-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wms-postgres-data:/var/lib/postgresql/data

volumes:
  wms-redis-data:
  wms-postgres-data:
